### ISSUE TITLE
Design the user interface

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-configure-fts#1]
The interface for this will live at `/-/enable-fts`. It needs to allow users to select specific columns from a table that they would like to make searchable. It also needs to be able to show them which columns are currently searchable.

**Comment by simonw** [comment]
I'm going to have a page for each database. `/-/enable-fts/database-name` - but if the current installation has only one database visiting `/-/enable-fts` will redirect straight there rather than showing a list of databases with only one item in it.

**Comment by simonw** [comment]
On that page-per-database it will show a list of tables with checkboxes for each of their text columns.

**Comment by theresia** [comment]
Hi Simon, I think I'm missing something obvious here but /-/configure-fts and /-/enable-fts both return "Database not found" for me. What's the configuration yml/json needed to configure this correctly? Thank you.
